name = "PiecewisePolynomials"
uuid = "be45d740-dee7-11e9-3cd8-1d315c23bbf9"
authors = ["Tatyana Abramova <loooj58@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
